# Generated by Django 5.0.3 on 2024-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefone', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
